// Standalone literal: no module closures or business storage dependencies.
const BOOTSTRAP = `(function(buildId, defaultEnabled) {
  try {
    if (window.__FLOAT_CRASH_DIAG_INTERNAL_V1__) return;
    var prefix='float:crashdiag:v1:';
    var keys={enabled:prefix+'enabled',current:prefix+'current',history:prefix+'history',suspect:prefix+'suspect'};
    var stages='GEN_TRIGGERED HISTORY_LOAD_BEGIN HISTORY_LOADED API_BEGIN API_FIRST_DELTA CONTEXT_PREP_BEGIN SHORT_TERM_BEGIN SHORT_TERM_READY MEMORY_RETRIEVAL_BEGIN LONG_TERM_READY CORE_MEMORY_READY MEMORY_RETRIEVAL_READY PROMPT_ASSEMBLY_BEGIN PROMPT_ASSEMBLED PROVIDER_PAYLOAD_BEGIN PROVIDER_REQUEST_BEGIN PROVIDER_RESPONSE_HEADERS PROVIDER_RESPONSE_RECEIVED RESPONSE_RECEIVED PARSE_DONE PUBLISHING PUBLISH_DONE MESSAGE_DISPATCH_BEGIN MESSAGE_DISPATCH_DONE GEN_ERROR GEN_FINALLY MEMORY_REVISION_READ_BEGIN MEMORY_REVISION_READ_DONE SHORT_TERM_ASSEMBLY_BEGIN SHORT_TERM_ASSEMBLY_DONE PROMPT_HISTORY_PREP_BEGIN PROMPT_HISTORY_PREP_DONE VISION_PREP_BEGIN VISION_PREP_DONE PUBLISH_ITEM_BEGIN PUSH_MESSAGE_RETURNED UI_STATE_QUEUED NOTICE_DISPATCH_DONE BROWSER_NOTIFICATION_CALLED PUBLISH_SYNC_DONE STAGGER_WAIT_BEGIN STAGGER_WAIT_DONE'.split(' ');
    var events='APP_CHANGE AI_RUN_START AI_RUN_END CANVAS_MOUNT CANVAS_UNMOUNT CANVAS_PAN_BEGIN CANVAS_PAN_END CANVAS_PINCH_BEGIN CANVAS_PINCH_END JS_ERROR VISIBILITY_CHANGE PAGEHIDE PAGESHOW_BFCACHE'.split(' ');
    var names='Error TypeError RangeError ReferenceError SyntaxError URIError EvalError AggregateError AbortError QuotaExceededError InvalidStateError NotFoundError SecurityError UnknownError NetworkError TimeoutError ChunkLoadError OtherError'.split(' ');
    var evidence='UNOBSERVED_FOREGROUND_END PAGEHIDE_OBSERVED BACKGROUND_OR_SUSPENDED UNKNOWN'.split(' ');
    var enabled=defaultEnabled, current=null, initialized=false, loadedDisabled=false;
    function n(v) { return typeof v==='number' && Number.isFinite(v) && v>=0?Math.min(1000000000,Math.floor(v)):0; }
    function time(v) { return typeof v==='number' && Number.isFinite(v) && v>=0 && v<=8640000000000000?v:0; }
    // Accept only opaque IDs generated by the existing foreground/background entry points.
    function id(v) { return typeof v==='string' && /^(?:[0-9]{10,16}-[a-z0-9]{1,32}|bg_[0-9]{10,16}_[a-z0-9]{1,16})$/.test(v); }
    function raw(key,max) { try { var s=window.localStorage.getItem(key); return s && s.length<=max?JSON.parse(s):null; } catch (_) { return null; } }
    function put(key,value,max) { try { var s=JSON.stringify(value); if(s.length>max)return false; window.localStorage.setItem(key,s); return true; } catch(_){return false;} }
    function generation(r,runId) {
      if(!r || r.version!==1 || r.runId!==runId || !id(runId) || stages.indexOf(r.lastStage)<0 || typeof r.completed!=='boolean'
        || !time(r.startedAt) || !time(r.lastStageAt) || [r.historyCount,r.draftCount,r.publishedCount].some(function(v){return typeof v!=='number'||!Number.isFinite(v)||v<0;}))return null;
      return {runId:runId,status:'available',source:r.source==='background'?'background':r.source==='chatroom'?'chatroom':'unknown',
        lastStage:r.lastStage,startedAt:time(r.startedAt),lastStageAt:time(r.lastStageAt),completed:r.completed,
        historyCount:n(r.historyCount),draftCount:n(r.draftCount),publishedCount:n(r.publishedCount)};
    }
    function snapshots(ids) {
      if(!ids.length)return [];
      var records=[];
      for(var i=0;i<8;i++)records.push(raw('ai_phone_chat_generation_diag_slot_'+i+'_v1',4096));
      records.push(raw('ai_phone_chat_generation_diag_current_v1',4096),raw('ai_phone_chat_generation_diag_previous_v1',4096));
      return ids.map(function(runId){var best=null;records.forEach(function(r){var g=generation(r,runId);if(g && (!best || g.lastStageAt>best.lastStageAt))best=g;});return best||{runId:runId,status:'not_available'};});
    }
    function session(r) {
      if(!r || r.version!==1 || typeof r.documentId!=='string' || !/^[a-z0-9-]{1,64}$/.test(r.documentId)
        || typeof r.buildId!=='string' || !/^[a-zA-Z0-9._-]{1,80}$/.test(r.buildId) || !time(r.startedAt) || !time(r.lastRecordedAt))return null;
      var ids=[], recent=[];
      if(Array.isArray(r.activeGenerationRunIds))r.activeGenerationRunIds.slice(0,8).forEach(function(v){if(id(v)&&ids.indexOf(v)<0)ids.push(v);});
      if(Array.isArray(r.recentEvents))r.recentEvents.slice(-16).forEach(function(e){if(e&&events.indexOf(e.kind)>=0){var x={t:time(e.t),kind:e.kind};if(typeof e.v==='number')x.v=n(e.v);recent.push(x);}});
      var s={version:1,documentId:r.documentId,buildId:r.buildId,startedAt:r.startedAt,lastRecordedAt:r.lastRecordedAt,
        app:['desktop','chat','characters','settings','other'].indexOf(r.app)>=0?r.app:'unknown',
        visibility:['visible','hidden'].indexOf(r.visibility)>=0?r.visibility:'unknown',pagehideObserved:r.pagehideObserved===true,activeGenerationRunIds:ids,recentEvents:recent};
      if(typeof r.pagehidePersisted==='boolean')s.pagehidePersisted=r.pagehidePersisted;
      if(typeof r.pageshowFromBFCache==='boolean')s.pageshowFromBFCache=r.pageshowFromBFCache;
      if(r.observationGap===true)s.observationGap=true;
      if(events.indexOf(r.lastActivity)>=0)s.lastActivity=r.lastActivity;
      if(r.canvas)s.canvas={mounted:r.canvas.mounted===true,renderedCards:n(r.canvas.renderedCards),backgrounds:n(r.canvas.backgrounds),relations:n(r.canvas.relations),gesture:['pan','pinch'].indexOf(r.canvas.gesture)>=0?r.canvas.gesture:'none'};
      if(r.jsErrors)s.jsErrors={count:n(r.jsErrors.count),lastKind:r.jsErrors.lastKind==='unhandledrejection'?'unhandledrejection':'error',lastName:names.indexOf(r.jsErrors.lastName)>=0?r.jsErrors.lastName:'OtherError'};
      return s;
    }
    function archived(r) {
      var s=session(r);if(!s || !time(r.recoveredAt) || evidence.indexOf(r.evidence)<0)return null;
      s.recoveredAt=r.recoveredAt;s.evidence=r.evidence;s.systemTerminationReason='unknown';s.generationSnapshots=[];
      if(Array.isArray(r.generationSnapshots))r.generationSnapshots.slice(0,8).forEach(function(g){
        if(!g || s.activeGenerationRunIds.indexOf(g.runId)<0 || s.generationSnapshots.some(function(x){return x.runId===g.runId;}))return;
        var safe=g.status==='available'?generation(Object.assign({version:1},g),g.runId):null;
        s.generationSnapshots.push(safe||{runId:g.runId,status:'not_available'});
      });
      return s;
    }
    function history(){var r=raw(keys.history,65536);return Array.isArray(r)?r.slice(-8).map(archived).filter(Boolean):[];}
    function classify(s,now){
      // Without heartbeat, stale records or clock changes cannot locate document termination.
      if(s.observationGap || now<s.lastRecordedAt || now-s.lastRecordedAt>30*60*1000)return 'UNKNOWN';
      if(s.pagehideObserved)return 'PAGEHIDE_OBSERVED';
      if(s.visibility==='hidden')return 'BACKGROUND_OR_SUSPENDED';
      return s.visibility==='visible'?'UNOBSERVED_FOREGROUND_END':'UNKNOWN';
    }
    function init(){
      if(initialized)return;initialized=true;
      var now=Date.now(),old=session(raw(keys.current,8192));
      if(old){
        var a=Object.assign(old,{recoveredAt:now,evidence:loadedDisabled?'UNKNOWN':classify(old,now),systemTerminationReason:'unknown',generationSnapshots:snapshots(old.activeGenerationRunIds)});
        // Capture stages before new generation slots can overwrite the previous document.
        if(a.evidence==='UNOBSERVED_FOREGROUND_END')put(keys.suspect,a,8192);
        var h=history();h.push(a);h=h.slice(-8);while(h.length&&JSON.stringify(h).length>65536)h.shift();put(keys.history,h,65536);
      }
      current={version:1,documentId:now.toString(36)+'-'+Math.random().toString(36).slice(2,12),buildId:buildId,startedAt:now,lastRecordedAt:now,
        app:'unknown',visibility:document.visibilityState==='visible'?'visible':document.visibilityState==='hidden'?'hidden':'unknown',pagehideObserved:false,activeGenerationRunIds:[],recentEvents:[]};
      put(keys.current,current,8192);
    }
    function persist(kind,value){
      if(!enabled || !current)return;
      var owner=session(raw(keys.current,8192));if(owner && owner.documentId!==current.documentId)return;
      var now=Date.now(),e={t:now,kind:kind};if(typeof value==='number')e.v=n(value);
      current.lastActivity=kind;current.recentEvents.push(e);current.recentEvents=current.recentEvents.slice(-16);
      var candidate=session(Object.assign({},current,{lastRecordedAt:now}));
      if(put(keys.current,candidate,8192))current.lastRecordedAt=now;
    }
    function guard(fn){return function(){try{return fn.apply(null,arguments);}catch(_){}};}
    try{var setting=window.localStorage.getItem(keys.enabled);if(setting==='true'||setting==='false')enabled=setting==='true';}catch(_){enabled=false;}
    loadedDisabled=!enabled;
    if(enabled)init();
    var bridge={
      setEnabled:guard(function(v){if(typeof v!=='boolean'||v===enabled)return;if(!put(keys.enabled,v,16))return;enabled=v;if(!enabled&&current)current.observationGap=true;if(enabled){if(!initialized)init();else{current.activeGenerationRunIds=[];persist('APP_CHANGE');}}}),
      clear:guard(function(){['current','history','suspect'].forEach(function(k){try{window.localStorage.removeItem(keys[k]);}catch(_){}});}),
      runStart:guard(function(runId,source){if(!enabled||!current||!id(runId)||['chatroom','background'].indexOf(source)<0||current.activeGenerationRunIds.indexOf(runId)>=0||current.activeGenerationRunIds.length>=8)return;current.activeGenerationRunIds.push(runId);persist('AI_RUN_START',current.activeGenerationRunIds.length);}),
      runEnd:guard(function(runId){if(!enabled||!current)return;var i=current.activeGenerationRunIds.indexOf(runId);if(i<0)return;current.activeGenerationRunIds.splice(i,1);persist('AI_RUN_END',current.activeGenerationRunIds.length);}),
      app:guard(function(app){if(!enabled||!current||['desktop','chat','characters','settings','other'].indexOf(app)<0||current.app===app)return;current.app=app;persist('APP_CHANGE');}),
      canvas:guard(function(mounted,cards,backgrounds,relations,force){if(!enabled||!current)return;var next={mounted:mounted===true,renderedCards:n(cards),backgrounds:n(backgrounds),relations:n(relations),gesture:mounted && current.canvas && current.canvas.mounted?current.canvas.gesture:'none'};if(!force&&JSON.stringify(current.canvas)===JSON.stringify(next))return;current.canvas=next;persist(next.mounted?'CANVAS_MOUNT':'CANVAS_UNMOUNT');}),
      gesture:guard(function(kind,begin){if(!enabled||!current||!current.canvas||!current.canvas.mounted||['pan','pinch'].indexOf(kind)<0||typeof begin!=='boolean')return;if(begin&&current.canvas.gesture===kind||!begin&&current.canvas.gesture!==kind)return;current.canvas.gesture=begin?kind:'none';persist('CANVAS_'+kind.toUpperCase()+(begin?'_BEGIN':'_END'));}),
      read:guard(function(){var s=session(raw(keys.current,8192));return {enabled:enabled,current:s?Object.assign(s,{generationSnapshots:snapshots(s.activeGenerationRunIds),systemTerminationReason:'unknown'}):null,history:history(),suspect:archived(raw(keys.suspect,8192))};})
    };
    window.__FLOAT_CRASH_DIAG_INTERNAL_V1__=bridge;
    document.addEventListener('visibilitychange',guard(function(){if(!enabled||!current)return;var v=document.visibilityState==='visible'?'visible':document.visibilityState==='hidden'?'hidden':'unknown';if(v===current.visibility)return;current.visibility=v;persist('VISIBILITY_CHANGE');}));
    window.addEventListener('pagehide',guard(function(e){if(!enabled||!current||current.pagehideObserved&&current.pagehidePersisted===!!e.persisted)return;current.pagehideObserved=true;current.pagehidePersisted=!!e.persisted;persist('PAGEHIDE');}));
    window.addEventListener('pageshow',guard(function(e){if(!enabled||!current||!e.persisted)return;current.pageshowFromBFCache=true;current.pagehideObserved=false;delete current.pagehidePersisted;current.visibility=document.visibilityState==='visible'?'visible':'hidden';persist('PAGESHOW_BFCACHE');}));
    function jsError(kind,error){if(!enabled||!current||current.jsErrors&&current.jsErrors.count>=8)return;var name=error&&error.name;current.jsErrors={count:(current.jsErrors?current.jsErrors.count:0)+1,lastKind:kind,lastName:names.indexOf(name)>=0?name:'OtherError'};persist('JS_ERROR',current.jsErrors.count);}
    window.addEventListener('error',guard(function(e){jsError('error',e.error);}),true);
    window.addEventListener('unhandledrejection',guard(function(e){jsError('unhandledrejection',e.reason);}));
  }catch(_){}
})`;
export function crashDiagnosticsScript(buildId: string, defaultEnabled = true): string {
    const safeBuildId = /^[a-zA-Z0-9._-]{1,80}$/.test(buildId) ? buildId : "unknown";
    return BOOTSTRAP + "(" + JSON.stringify(safeBuildId) + "," + defaultEnabled + ");";
}
